### ISSUE TITLE
图片乱序

### ISSUE THREAD

**Issue by smuyyh** [zengcanxiang/BaseAdapter#1]
在recyclerview HelperViewHolder的setImgUrl里，用Glide或Picasso加载图片都会错位~  请问有没有碰到这问题

**Comment by zengcanxiang** [comment]
这个还没碰到过,我最近项目紧，晚上抽些时间看看

**Comment by zengcanxiang** [comment]
@smuyyh 我这边测试的时候图片不会说重复乱序,对应的item也没有显示相同的图片,所对应的图片位置也是没有问题的.不知道是不是你的界面比较复杂还是业务逻辑复杂了么？
我打印了view的tag，最开始会有一些tag相同，但是反复移动这个tag也在不停的变化,这个应该是没有影响的
![qq 20160615225619](https://cloud.githubusercontent.com/assets/16033497/16084836/bb94e990-334c-11e6-8f38-eaac420ec5d0.png)

**Comment by smuyyh** [comment]
@zengcanxiang 对的。我在模拟器上、米3 都不会。但是小米1就会..  可能低端机性能不行导致的吧~   还是谢谢你啦~~

**Comment by zengcanxiang** [comment]
可以就行，没什么说谢不谢的，交流交流
