### ISSUE TITLE
五毛钱的建议，哈哈

### ISSUE THREAD

**Issue by Yieron** [zengcanxiang/BaseAdapter#2]
1：把项目提出来，让直接下载就能跑起来，这样使用的人会越来越多，要不然，下载后跑不起来，很多人会望而却步。
2：在readme文档中写上把
//apply plugin: 'com.github.dcendents.android-maven'
//install {
//    repositories.mavenInstaller {
//        // This generates POM.xml with proper parameters
//        pom {
//            project {
//                packaging 'aar'
//                // Add your description here
//                name 'encapsulation abslistView and recyclerView adapter' 	//项目描述
//                url siteUrl
//                // Set your license
//                licenses {
//                    license {
//                        name 'The Apache Software License, Version 2.0'
//                        url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
//                    }
//                }
//                developers {
//                    developer {
//                        id 'zengcanxiang'		//填写的一些基本信息
//                        name 'zengcanxiang'
//                        email 'zengcanxiang@gmail.com'
//                    }
//                }
//                scm {
//                    connection gitUrl
//                    developerConnection gitUrl
//                    url siteUrl
//                }
//            }
//        }
//    }
//}
这些注释掉，就能跑起来。这样很多技术控都会玩的。

**Comment by zengcanxiang** [comment]
谢谢

**Comment by zengcanxiang** [comment]
@Yieron 已经提供apk下载。以及最新代码及版本
